version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node
    environment:
      HEROKU_APP_NAME: trabalho-devops
      HEROKU_API_KEY: 94c447cc-c508-4238-a454-ee7aca171bca
    steps:
      - checkout
      - run:
          name: Test Heroku availability
          command: |
            if [[ $(curl -Is https://${HEROKU_APP_NAME}.herokuapp.com | head -1) == *"200"* ]]; then
              echo "Heroku available"
            else
              echo "Heroku unavailable"
              Erro: "Heroku unavailable"
            fi

  publish:
    docker:
      - image: circleci/node
    environment:
      GITHUB_REPO: https://github.com/trabalho-linux-cloud/trabalho-devops
      HEROKU_APP_NAME: trabalho-devops
      HEROKU_API_KEY: 94c447cc-c508-4238-a454-ee7aca171bca
      USER_EMAIL: trabalho.linux.cloud@gmail.com
      USER_NAME: Linux Cloud
      CIRCLE_BRANCH: master
    steps:
      - checkout
      - run:
          name: Install Heroku CLI (If not installed)      
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Push to Heroku master branch
          command: |
             cd ..
             git clone ${GITHUB_REPO} devops
             cd devops
             heroku access --app ${HEROKU_APP_NAME}
             touch "Change for commit" > init.txt
             git add .
             git config --global user.email ${USER_EMAIL}
             git config --global user.name ${USER_NAME}
             git commit -am "Commit Circle CI"       
             git push --force https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git ${CIRCLE_BRANCH}:master
  
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Heroku deploy
          command: |
              echo "The deployment is done in Heroku"

workflows:
  version: 2.1
  pipeline-master:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
